---
- name: Ensure the group exists for the docker user
  ansible.builtin.group:
    name: "{{ rootless_user }}"
    gid: "{{ rootless_user_id }}"
  become: true

- name: Create a rootless_user user
  ansible.builtin.user:
    name: "{{ rootless_user }}"
    state: present
    shell: /bin/bash
    password: "{{ rootless_user_password | password_hash('sha512') }}"
    uid: "{{ rootless_user_id }}"
    group: "{{ rootless_user }}"
  become: true

- name: Enable linger for rootless_user
  ansible.builtin.command: loginctl enable-linger {{ rootless_user }}
  changed_when: false
  become: true
